/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package musicservice;

import java.util.List;
import java.util.Arrays;

public class MusicCollectionService {
    public List<String> getMusicCollection() {
        return Arrays.asList("lama.mp3", "chumbawamba.mp3");
    }
}
